apiVersion: v1
kind: ConfigMap
metadata:
  name: servers-cm
data:
  # db: phonebook
  # user: clarus
  # db-host: mysql-service
  MYSQL_DATABASE_HOST: mysql-service
  MYSQL_DATABASE: phonebook
  MYSQL_USER: clarus