apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: omercan99/web
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: servers-cm  
#         env:
#         - name: MYSQL_DATABASE_HOST
# #         value: mysql-service
#           valueFrom:
#             configMapKeyRef:
#               name: servers-cm
#               key: db-host
#         - name: MYSQL_DATABASE
# #         value: phonebook
#           valueFrom:
#             configMapKeyRef:
#               name: servers-cm
#               key: db
#         - name: MYSQL_USER
# #         value: clarus
#           valueFrom:
#             configMapKeyRef:
#               name: servers-cm
#               key: user
#         - name: MYSQL_PASSWORD
# #         value: Clarusway_1
#           valueFrom:
#             secretKeyRef:
#               name: mysql-secret
#               key: pass